<a href="https://colab.research.google.com/github/alimovscott/ai-foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [3]:

# pandas version check
print(pd.__version__)

2.2.2

In [4]:
# DataFrame() - forms a tabular data

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [5]:
# head() - first 5 rows by default
df.head()

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [6]:
# tail() - last 5 rows by default
df.tail()

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.shape

In [7]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

In [8]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [9]:
df.describe()

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [10]:
df.describe(include="all")

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [11]:
# iloc - selects a specific row

df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [12]:
df.iloc[1:4] # [1, 4)

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [ ]:
df.iloc[2:] # [2, end]

In [ ]:
# loc[row, "column_name"]

df.loc[2:5, "cars"]

In [ ]:
# Conditional Selection / Filtering

df["counts"] > 3

In [13]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [14]:
df[df["counts"] <= 3]

      cars  counts
0      BMW       3
2     Ford       2
4  Ferrari       1
6      BMW       3

In [ ]:
df[df["cars"] == "BMW"]

In [ ]:
# df.mean(numeric_only=True)
df["counts"].mean()

In [ ]:
df.sum()

In [15]:

df.min()

cars      BMW
counts      1
dtype: object

In [16]:

df.max()

cars      Volvo
counts        9
dtype: object

In [ ]:

df.median(numeric_only=True)

In [ ]:
df.count() # Returns non null values only

In [ ]:

df.std(numeric_only=True)

In [17]:

# creating a dataset with missing data

data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "BMW"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6      BMW     NaN

In [ ]:
# counting missing data

df_missing.isnull().sum()

In [ ]:

# dropna() - deleting missing data

df_missing.dropna()
df_missing.dropna(how="all")  # checks by rows with all null data
df_missing.dropna(axis=1)     # checks by column
df_missing.dropna(subset=["counts"]) # checks by subsets

In [20]:

# fillna() - filling missing data

df_missing.fillna("unknown")
df_missing.fillna(0)

df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6      BMW     0.0